/** 365 unique quotes per role — one per calendar day (day-of-year index). */
const DAILY_QUOTES = {
  ceo: [
    "Think big. Act now.",
    "Decide fast. Deliver faster.",
    "Less noise. More impact.",
    "Win the morning, win the week.",
    "Pressure makes diamonds.",
    "Be the standard.",
    "Own the room. Own the day.",
    "Your energy is the culture.",
    "Bold calls build empires.",
    "Strategy beats hustle.",
    "Clarity is your superpower.",
    "Run the day \u2014 don't chase it.",
    "One sharp call changes everything.",
    "Big picture. Sharp execution.",
    "Trust your gut. Verify with data.",
    "Scale ideas, not chaos.",
    "Outwork the doubt.",
    "Today's focus = tomorrow's edge.",
    "Make today count twice.",
    "Stay hungry. Stay sharp.",
    "Lead with intent, not noise.",
    "Turn ambition into momentum.",
    "Excellence starts at the top.",
    "The bar rises with you.",
    "Build what others won't.",
    "Vision today, wins tomorrow.",
    "Your move sets the pace.",
    "Lead loud. Ship faster.",
    "Command calm. Move fast.",
    "Start strong. Stay stronger.",
    "Lead the vision.",
    "Lead the momentum.",
    "Lead the culture.",
    "Lead the strategy.",
    "Lead the execution.",
    "Lead the clarity.",
    "Lead the impact.",
    "Lead the growth.",
    "Lead the excellence.",
    "Lead the ambition.",
    "Lead the focus.",
    "Lead the discipline.",
    "Lead the courage.",
    "Lead the innovation.",
    "Lead the legacy.",
    "Lead the standards.",
    "Lead the results.",
    "Lead the teams.",
    "Lead the markets.",
    "Lead the opportunity.",
    "Build the vision.",
    "Build the momentum.",
    "Build the culture.",
    "Build the strategy.",
    "Build the execution.",
    "Build the clarity.",
    "Build the impact.",
    "Build the growth.",
    "Build the excellence.",
    "Build the ambition.",
    "Build the focus.",
    "Build the discipline.",
    "Build the courage.",
    "Build the innovation.",
    "Build the legacy.",
    "Build the standards.",
    "Build the results.",
    "Build the teams.",
    "Build the markets.",
    "Build the opportunity.",
    "Scale the vision.",
    "Scale the momentum.",
    "Scale the culture.",
    "Scale the strategy.",
    "Scale the execution.",
    "Scale the clarity.",
    "Scale the impact.",
    "Scale the growth.",
    "Scale the excellence.",
    "Scale the ambition.",
    "Scale the focus.",
    "Scale the discipline.",
    "Scale the courage.",
    "Scale the innovation.",
    "Scale the legacy.",
    "Scale the standards.",
    "Scale the results.",
    "Scale the teams.",
    "Scale the markets.",
    "Scale the opportunity.",
    "Drive the vision.",
    "Drive the momentum.",
    "Drive the culture.",
    "Drive the strategy.",
    "Drive the execution.",
    "Drive the clarity.",
    "Drive the impact.",
    "Drive the growth.",
    "Drive the excellence.",
    "Drive the ambition.",
    "Drive the focus.",
    "Drive the discipline.",
    "Drive the courage.",
    "Drive the innovation.",
    "Drive the legacy.",
    "Drive the standards.",
    "Drive the results.",
    "Drive the teams.",
    "Drive the markets.",
    "Drive the opportunity.",
    "Own the vision.",
    "Own the momentum.",
    "Own the culture.",
    "Own the strategy.",
    "Own the execution.",
    "Own the clarity.",
    "Own the impact.",
    "Own the growth.",
    "Own the excellence.",
    "Own the ambition.",
    "Own the focus.",
    "Own the discipline.",
    "Own the courage.",
    "Own the innovation.",
    "Own the legacy.",
    "Own the standards.",
    "Own the results.",
    "Own the teams.",
    "Own the markets.",
    "Own the opportunity.",
    "Shape the vision.",
    "Shape the momentum.",
    "Shape the culture.",
    "Shape the strategy.",
    "Shape the execution.",
    "Shape the clarity.",
    "Shape the impact.",
    "Shape the growth.",
    "Shape the excellence.",
    "Shape the ambition.",
    "Shape the focus.",
    "Shape the discipline.",
    "Shape the courage.",
    "Shape the innovation.",
    "Shape the legacy.",
    "Shape the standards.",
    "Shape the results.",
    "Shape the teams.",
    "Shape the markets.",
    "Shape the opportunity.",
    "Command the vision.",
    "Command the momentum.",
    "Command the culture.",
    "Command the strategy.",
    "Command the execution.",
    "Command the clarity.",
    "Command the impact.",
    "Command the growth.",
    "Command the excellence.",
    "Command the ambition.",
    "Command the focus.",
    "Command the discipline.",
    "Command the courage.",
    "Command the innovation.",
    "Command the legacy.",
    "Command the standards.",
    "Command the results.",
    "Command the teams.",
    "Command the markets.",
    "Command the opportunity.",
    "Fuel the vision.",
    "Fuel the momentum.",
    "Fuel the culture.",
    "Fuel the strategy.",
    "Fuel the execution.",
    "Fuel the clarity.",
    "Fuel the impact.",
    "Fuel the growth.",
    "Fuel the excellence.",
    "Fuel the ambition.",
    "Fuel the focus.",
    "Fuel the discipline.",
    "Fuel the courage.",
    "Fuel the innovation.",
    "Fuel the legacy.",
    "Fuel the standards.",
    "Fuel the results.",
    "Fuel the teams.",
    "Fuel the markets.",
    "Fuel the opportunity.",
    "Ignite the vision.",
    "Ignite the momentum.",
    "Ignite the culture.",
    "Ignite the strategy.",
    "Ignite the execution.",
    "Ignite the clarity.",
    "Ignite the impact.",
    "Ignite the growth.",
    "Ignite the excellence.",
    "Ignite the ambition.",
    "Ignite the focus.",
    "Ignite the discipline.",
    "Ignite the courage.",
    "Ignite the innovation.",
    "Ignite the legacy.",
    "Ignite the standards.",
    "Ignite the results.",
    "Ignite the teams.",
    "Ignite the markets.",
    "Ignite the opportunity.",
    "Steer the vision.",
    "Steer the momentum.",
    "Steer the culture.",
    "Steer the strategy.",
    "Steer the execution.",
    "Steer the clarity.",
    "Steer the impact.",
    "Steer the growth.",
    "Steer the excellence.",
    "Steer the ambition.",
    "Steer the focus.",
    "Steer the discipline.",
    "Steer the courage.",
    "Steer the innovation.",
    "Steer the legacy.",
    "Steer the standards.",
    "Steer the results.",
    "Steer the teams.",
    "Steer the markets.",
    "Steer the opportunity.",
    "Chart the vision.",
    "Chart the momentum.",
    "Chart the culture.",
    "Chart the strategy.",
    "Chart the execution.",
    "Chart the clarity.",
    "Chart the impact.",
    "Chart the growth.",
    "Chart the excellence.",
    "Chart the ambition.",
    "Chart the focus.",
    "Chart the discipline.",
    "Chart the courage.",
    "Chart the innovation.",
    "Chart the legacy.",
    "Chart the standards.",
    "Chart the results.",
    "Chart the teams.",
    "Chart the markets.",
    "Chart the opportunity.",
    "Pioneer the vision.",
    "Pioneer the momentum.",
    "Pioneer the culture.",
    "Pioneer the strategy.",
    "Pioneer the execution.",
    "Pioneer the clarity.",
    "Pioneer the impact.",
    "Pioneer the growth.",
    "Pioneer the excellence.",
    "Pioneer the ambition.",
    "Pioneer the focus.",
    "Pioneer the discipline.",
    "Pioneer the courage.",
    "Pioneer the innovation.",
    "Pioneer the legacy.",
    "Pioneer the standards.",
    "Pioneer the results.",
    "Pioneer the teams.",
    "Pioneer the markets.",
    "Pioneer the opportunity.",
    "Elevate the vision.",
    "Elevate the momentum.",
    "Elevate the culture.",
    "Elevate the strategy.",
    "Elevate the execution.",
    "Elevate the clarity.",
    "Elevate the impact.",
    "Elevate the growth.",
    "Elevate the excellence.",
    "Elevate the ambition.",
    "Elevate the focus.",
    "Elevate the discipline.",
    "Elevate the courage.",
    "Elevate the innovation.",
    "Elevate the legacy.",
    "Elevate the standards.",
    "Elevate the results.",
    "Elevate the teams.",
    "Elevate the markets.",
    "Elevate the opportunity.",
    "Amplify the vision.",
    "Amplify the momentum.",
    "Amplify the culture.",
    "Amplify the strategy.",
    "Amplify the execution.",
    "Amplify the clarity.",
    "Amplify the impact.",
    "Amplify the growth.",
    "Amplify the excellence.",
    "Amplify the ambition.",
    "Amplify the focus.",
    "Amplify the discipline.",
    "Amplify the courage.",
    "Amplify the innovation.",
    "Amplify the legacy.",
    "Amplify the standards.",
    "Amplify the results.",
    "Amplify the teams.",
    "Amplify the markets.",
    "Amplify the opportunity.",
    "Orchestrate the vision.",
    "Orchestrate the momentum.",
    "Orchestrate the culture.",
    "Orchestrate the strategy.",
    "Orchestrate the execution.",
    "Orchestrate the clarity.",
    "Orchestrate the impact.",
    "Orchestrate the growth.",
    "Orchestrate the excellence.",
    "Orchestrate the ambition.",
    "Orchestrate the focus.",
    "Orchestrate the discipline.",
    "Orchestrate the courage.",
    "Orchestrate the innovation.",
    "Orchestrate the legacy.",
    "Orchestrate the standards.",
    "Orchestrate the results.",
    "Orchestrate the teams.",
    "Orchestrate the markets.",
    "Orchestrate the opportunity.",
    "Cultivate the vision.",
    "Cultivate the momentum.",
    "Cultivate the culture.",
    "Cultivate the strategy.",
    "Cultivate the execution.",
    "Cultivate the clarity.",
    "Cultivate the impact.",
    "Cultivate the growth.",
    "Cultivate the excellence.",
    "Cultivate the ambition.",
    "Cultivate the focus.",
    "Cultivate the discipline.",
    "Cultivate the courage.",
    "Cultivate the innovation.",
    "Cultivate the legacy.",
    "Cultivate the standards.",
    "Cultivate the results.",
    "Cultivate the teams.",
    "Cultivate the markets.",
    "Cultivate the opportunity.",
    "Champion the vision.",
    "Champion the momentum.",
    "Champion the culture.",
    "Champion the strategy.",
    "Champion the execution.",
    "Champion the clarity.",
    "Champion the impact.",
    "Champion the growth.",
    "Champion the excellence.",
    "Champion the ambition.",
    "Champion the focus.",
    "Champion the discipline.",
    "Champion the courage.",
    "Champion the innovation.",
    "Champion the legacy.",
  ],
  manager: [
    "Unblock one person, win the day.",
    "Your team feels your vibe.",
    "Guide. Don't micromanage.",
    "Clear path, fast sprint.",
    "Rally the crew. Ship it.",
    "Small wins stack big.",
    "Listen first. Lead second.",
    "Be the glue today.",
    "Progress over perfection.",
    "Remove friction. Add fuel.",
    "Ship before sunset.",
    "Be the answer, not the bottleneck.",
    "One clear goal beats ten vague ones.",
    "Team energy starts with you.",
    "Make work feel winnable.",
    "Praise in public. Fix in private.",
    "Stay sharp. Stay kind.",
    "Lead from the trenches.",
    "Today: unblock, align, deliver.",
    "Your calm is contagious.",
    "Celebrate the grind.",
    "Coach in the moment.",
    "Plans are nothing without pace.",
    "Earn trust in small moments.",
    "Protect focus. Kill distractions.",
    "Show up loud for your team.",
    "Turn chaos into a checklist.",
    "Momentum loves a manager.",
    "Your 1:1s move mountains.",
    "Make the hard call early.",
    "Rally the team.",
    "Rally the sprint.",
    "Rally the focus.",
    "Rally the pace.",
    "Rally the clarity.",
    "Rally the trust.",
    "Rally the rhythm.",
    "Rally the progress.",
    "Rally the morale.",
    "Rally the goals.",
    "Rally the blockers.",
    "Rally the wins.",
    "Rally the energy.",
    "Rally the momentum.",
    "Rally the standards.",
    "Rally the check-ins.",
    "Rally the delivery.",
    "Rally the collaboration.",
    "Rally the feedback.",
    "Rally the execution.",
    "Guide the team.",
    "Guide the sprint.",
    "Guide the focus.",
    "Guide the pace.",
    "Guide the clarity.",
    "Guide the trust.",
    "Guide the rhythm.",
    "Guide the progress.",
    "Guide the morale.",
    "Guide the goals.",
    "Guide the blockers.",
    "Guide the wins.",
    "Guide the energy.",
    "Guide the momentum.",
    "Guide the standards.",
    "Guide the check-ins.",
    "Guide the delivery.",
    "Guide the collaboration.",
    "Guide the feedback.",
    "Guide the execution.",
    "Unblock the team.",
    "Unblock the sprint.",
    "Unblock the focus.",
    "Unblock the pace.",
    "Unblock the clarity.",
    "Unblock the trust.",
    "Unblock the rhythm.",
    "Unblock the progress.",
    "Unblock the morale.",
    "Unblock the goals.",
    "Unblock the blockers.",
    "Unblock the wins.",
    "Unblock the energy.",
    "Unblock the momentum.",
    "Unblock the standards.",
    "Unblock the check-ins.",
    "Unblock the delivery.",
    "Unblock the collaboration.",
    "Unblock the feedback.",
    "Unblock the execution.",
    "Coach the team.",
    "Coach the sprint.",
    "Coach the focus.",
    "Coach the pace.",
    "Coach the clarity.",
    "Coach the trust.",
    "Coach the rhythm.",
    "Coach the progress.",
    "Coach the morale.",
    "Coach the goals.",
    "Coach the blockers.",
    "Coach the wins.",
    "Coach the energy.",
    "Coach the momentum.",
    "Coach the standards.",
    "Coach the check-ins.",
    "Coach the delivery.",
    "Coach the collaboration.",
    "Coach the feedback.",
    "Coach the execution.",
    "Align the team.",
    "Align the sprint.",
    "Align the focus.",
    "Align the pace.",
    "Align the clarity.",
    "Align the trust.",
    "Align the rhythm.",
    "Align the progress.",
    "Align the morale.",
    "Align the goals.",
    "Align the blockers.",
    "Align the wins.",
    "Align the energy.",
    "Align the momentum.",
    "Align the standards.",
    "Align the check-ins.",
    "Align the delivery.",
    "Align the collaboration.",
    "Align the feedback.",
    "Align the execution.",
    "Shield the team.",
    "Shield the sprint.",
    "Shield the focus.",
    "Shield the pace.",
    "Shield the clarity.",
    "Shield the trust.",
    "Shield the rhythm.",
    "Shield the progress.",
    "Shield the morale.",
    "Shield the goals.",
    "Shield the blockers.",
    "Shield the wins.",
    "Shield the energy.",
    "Shield the momentum.",
    "Shield the standards.",
    "Shield the check-ins.",
    "Shield the delivery.",
    "Shield the collaboration.",
    "Shield the feedback.",
    "Shield the execution.",
    "Boost the team.",
    "Boost the sprint.",
    "Boost the focus.",
    "Boost the pace.",
    "Boost the clarity.",
    "Boost the trust.",
    "Boost the rhythm.",
    "Boost the progress.",
    "Boost the morale.",
    "Boost the goals.",
    "Boost the blockers.",
    "Boost the wins.",
    "Boost the energy.",
    "Boost the momentum.",
    "Boost the standards.",
    "Boost the check-ins.",
    "Boost the delivery.",
    "Boost the collaboration.",
    "Boost the feedback.",
    "Boost the execution.",
    "Clear the team.",
    "Clear the sprint.",
    "Clear the focus.",
    "Clear the pace.",
    "Clear the clarity.",
    "Clear the trust.",
    "Clear the rhythm.",
    "Clear the progress.",
    "Clear the morale.",
    "Clear the goals.",
    "Clear the blockers.",
    "Clear the wins.",
    "Clear the energy.",
    "Clear the momentum.",
    "Clear the standards.",
    "Clear the check-ins.",
    "Clear the delivery.",
    "Clear the collaboration.",
    "Clear the feedback.",
    "Clear the execution.",
    "Support the team.",
    "Support the sprint.",
    "Support the focus.",
    "Support the pace.",
    "Support the clarity.",
    "Support the trust.",
    "Support the rhythm.",
    "Support the progress.",
    "Support the morale.",
    "Support the goals.",
    "Support the blockers.",
    "Support the wins.",
    "Support the energy.",
    "Support the momentum.",
    "Support the standards.",
    "Support the check-ins.",
    "Support the delivery.",
    "Support the collaboration.",
    "Support the feedback.",
    "Support the execution.",
    "Empower the team.",
    "Empower the sprint.",
    "Empower the focus.",
    "Empower the pace.",
    "Empower the clarity.",
    "Empower the trust.",
    "Empower the rhythm.",
    "Empower the progress.",
    "Empower the morale.",
    "Empower the goals.",
    "Empower the blockers.",
    "Empower the wins.",
    "Empower the energy.",
    "Empower the momentum.",
    "Empower the standards.",
    "Empower the check-ins.",
    "Empower the delivery.",
    "Empower the collaboration.",
    "Empower the feedback.",
    "Empower the execution.",
    "Motivate the team.",
    "Motivate the sprint.",
    "Motivate the focus.",
    "Motivate the pace.",
    "Motivate the clarity.",
    "Motivate the trust.",
    "Motivate the rhythm.",
    "Motivate the progress.",
    "Motivate the morale.",
    "Motivate the goals.",
    "Motivate the blockers.",
    "Motivate the wins.",
    "Motivate the energy.",
    "Motivate the momentum.",
    "Motivate the standards.",
    "Motivate the check-ins.",
    "Motivate the delivery.",
    "Motivate the collaboration.",
    "Motivate the feedback.",
    "Motivate the execution.",
    "Streamline the team.",
    "Streamline the sprint.",
    "Streamline the focus.",
    "Streamline the pace.",
    "Streamline the clarity.",
    "Streamline the trust.",
    "Streamline the rhythm.",
    "Streamline the progress.",
    "Streamline the morale.",
    "Streamline the goals.",
    "Streamline the blockers.",
    "Streamline the wins.",
    "Streamline the energy.",
    "Streamline the momentum.",
    "Streamline the standards.",
    "Streamline the check-ins.",
    "Streamline the delivery.",
    "Streamline the collaboration.",
    "Streamline the feedback.",
    "Streamline the execution.",
    "Celebrate the team.",
    "Celebrate the sprint.",
    "Celebrate the focus.",
    "Celebrate the pace.",
    "Celebrate the clarity.",
    "Celebrate the trust.",
    "Celebrate the rhythm.",
    "Celebrate the progress.",
    "Celebrate the morale.",
    "Celebrate the goals.",
    "Celebrate the blockers.",
    "Celebrate the wins.",
    "Celebrate the energy.",
    "Celebrate the momentum.",
    "Celebrate the standards.",
    "Celebrate the check-ins.",
    "Celebrate the delivery.",
    "Celebrate the collaboration.",
    "Celebrate the feedback.",
    "Celebrate the execution.",
    "Protect the team.",
    "Protect the sprint.",
    "Protect the focus.",
    "Protect the pace.",
    "Protect the clarity.",
    "Protect the trust.",
    "Protect the rhythm.",
    "Protect the progress.",
    "Protect the morale.",
    "Protect the goals.",
    "Protect the blockers.",
    "Protect the wins.",
    "Protect the energy.",
    "Protect the momentum.",
    "Protect the standards.",
    "Protect the check-ins.",
    "Protect the delivery.",
    "Protect the collaboration.",
    "Protect the feedback.",
    "Protect the execution.",
    "Enable the team.",
    "Enable the sprint.",
    "Enable the focus.",
    "Enable the pace.",
    "Enable the clarity.",
    "Enable the trust.",
    "Enable the rhythm.",
    "Enable the progress.",
    "Enable the morale.",
    "Enable the goals.",
    "Enable the blockers.",
    "Enable the wins.",
    "Enable the energy.",
    "Enable the momentum.",
    "Enable the standards.",
    "Enable the check-ins.",
    "Enable the delivery.",
    "Enable the collaboration.",
    "Enable the feedback.",
    "Enable the execution.",
    "Inspire the team.",
    "Inspire the sprint.",
    "Inspire the focus.",
    "Inspire the pace.",
    "Inspire the clarity.",
    "Inspire the trust.",
    "Inspire the rhythm.",
    "Inspire the progress.",
    "Inspire the morale.",
    "Inspire the goals.",
    "Inspire the blockers.",
    "Inspire the wins.",
    "Inspire the energy.",
    "Inspire the momentum.",
    "Inspire the standards.",
    "Inspire the check-ins.",
    "Inspire the delivery.",
    "Inspire the collaboration.",
    "Inspire the feedback.",
    "Inspire the execution.",
    "Organize the team.",
    "Organize the sprint.",
    "Organize the focus.",
    "Organize the pace.",
    "Organize the clarity.",
    "Organize the trust.",
    "Organize the rhythm.",
    "Organize the progress.",
    "Organize the morale.",
    "Organize the goals.",
    "Organize the blockers.",
    "Organize the wins.",
    "Organize the energy.",
    "Organize the momentum.",
    "Organize the standards.",
  ],
  employee: [
    "Show up. Stand out.",
    "One task closer to done.",
    "Focus beats frenzy.",
    "Small steps. Big payoff.",
    "You've got this \u2014 prove it.",
    "Checked in? Already winning.",
    "Do the work. Own the result.",
    "Progress > perfect.",
    "Make today your best rep.",
    "Deep breath. Deep work.",
    "Finish what you start.",
    "Hustle with heart.",
    "Crush the next task.",
    "Stay curious. Stay sharp.",
    "Done is better than perfect.",
    "Bring the energy.",
    "Quiet grind, loud results.",
    "One win at a time.",
    "No zero days.",
    "Work smart. Win daily.",
    "Rise. Grind. Repeat.",
    "Today is yours to shape.",
    "Outdo yesterday's you.",
    "Be the teammate you'd want.",
    "Turn effort into excellence.",
    "Start messy. Finish strong.",
    "Your focus fuels the team.",
    "Make it count today.",
    "Learn something. Ship something.",
    "Keep the streak alive.",
    "Show the focus.",
    "Show the momentum.",
    "Show the progress.",
    "Show the tasks.",
    "Show the goals.",
    "Show the effort.",
    "Show the craft.",
    "Show the hustle.",
    "Show the discipline.",
    "Show the curiosity.",
    "Show the results.",
    "Show the streak.",
    "Show the energy.",
    "Show the details.",
    "Show the deadlines.",
    "Show the growth.",
    "Show the pride.",
    "Show the pace.",
    "Show the impact.",
    "Show the grind.",
    "Crush the focus.",
    "Crush the momentum.",
    "Crush the progress.",
    "Crush the tasks.",
    "Crush the goals.",
    "Crush the effort.",
    "Crush the craft.",
    "Crush the hustle.",
    "Crush the discipline.",
    "Crush the curiosity.",
    "Crush the results.",
    "Crush the streak.",
    "Crush the energy.",
    "Crush the details.",
    "Crush the deadlines.",
    "Crush the growth.",
    "Crush the pride.",
    "Crush the pace.",
    "Crush the impact.",
    "Crush the grind.",
    "Own the focus.",
    "Own the momentum.",
    "Own the progress.",
    "Own the tasks.",
    "Own the goals.",
    "Own the effort.",
    "Own the craft.",
    "Own the hustle.",
    "Own the discipline.",
    "Own the curiosity.",
    "Own the results.",
    "Own the streak.",
    "Own the energy.",
    "Own the details.",
    "Own the deadlines.",
    "Own the growth.",
    "Own the pride.",
    "Own the pace.",
    "Own the impact.",
    "Own the grind.",
    "Finish the focus.",
    "Finish the momentum.",
    "Finish the progress.",
    "Finish the tasks.",
    "Finish the goals.",
    "Finish the effort.",
    "Finish the craft.",
    "Finish the hustle.",
    "Finish the discipline.",
    "Finish the curiosity.",
    "Finish the results.",
    "Finish the streak.",
    "Finish the energy.",
    "Finish the details.",
    "Finish the deadlines.",
    "Finish the growth.",
    "Finish the pride.",
    "Finish the pace.",
    "Finish the impact.",
    "Finish the grind.",
    "Start the focus.",
    "Start the momentum.",
    "Start the progress.",
    "Start the tasks.",
    "Start the goals.",
    "Start the effort.",
    "Start the craft.",
    "Start the hustle.",
    "Start the discipline.",
    "Start the curiosity.",
    "Start the results.",
    "Start the streak.",
    "Start the energy.",
    "Start the details.",
    "Start the deadlines.",
    "Start the growth.",
    "Start the pride.",
    "Start the pace.",
    "Start the impact.",
    "Start the grind.",
    "Keep the focus.",
    "Keep the momentum.",
    "Keep the progress.",
    "Keep the tasks.",
    "Keep the goals.",
    "Keep the effort.",
    "Keep the craft.",
    "Keep the hustle.",
    "Keep the discipline.",
    "Keep the curiosity.",
    "Keep the results.",
    "Keep the streak.",
    "Keep the energy.",
    "Keep the details.",
    "Keep the deadlines.",
    "Keep the growth.",
    "Keep the pride.",
    "Keep the pace.",
    "Keep the impact.",
    "Keep the grind.",
    "Push the focus.",
    "Push the momentum.",
    "Push the progress.",
    "Push the tasks.",
    "Push the goals.",
    "Push the effort.",
    "Push the craft.",
    "Push the hustle.",
    "Push the discipline.",
    "Push the curiosity.",
    "Push the results.",
    "Push the streak.",
    "Push the energy.",
    "Push the details.",
    "Push the deadlines.",
    "Push the growth.",
    "Push the pride.",
    "Push the pace.",
    "Push the impact.",
    "Push the grind.",
    "Build the focus.",
    "Build the momentum.",
    "Build the progress.",
    "Build the tasks.",
    "Build the goals.",
    "Build the effort.",
    "Build the craft.",
    "Build the hustle.",
    "Build the discipline.",
    "Build the curiosity.",
    "Build the results.",
    "Build the streak.",
    "Build the energy.",
    "Build the details.",
    "Build the deadlines.",
    "Build the growth.",
    "Build the pride.",
    "Build the pace.",
    "Build the impact.",
    "Build the grind.",
    "Learn the focus.",
    "Learn the momentum.",
    "Learn the progress.",
    "Learn the tasks.",
    "Learn the goals.",
    "Learn the effort.",
    "Learn the craft.",
    "Learn the hustle.",
    "Learn the discipline.",
    "Learn the curiosity.",
    "Learn the results.",
    "Learn the streak.",
    "Learn the energy.",
    "Learn the details.",
    "Learn the deadlines.",
    "Learn the growth.",
    "Learn the pride.",
    "Learn the pace.",
    "Learn the impact.",
    "Learn the grind.",
    "Deliver the focus.",
    "Deliver the momentum.",
    "Deliver the progress.",
    "Deliver the tasks.",
    "Deliver the goals.",
    "Deliver the effort.",
    "Deliver the craft.",
    "Deliver the hustle.",
    "Deliver the discipline.",
    "Deliver the curiosity.",
    "Deliver the results.",
    "Deliver the streak.",
    "Deliver the energy.",
    "Deliver the details.",
    "Deliver the deadlines.",
    "Deliver the growth.",
    "Deliver the pride.",
    "Deliver the pace.",
    "Deliver the impact.",
    "Deliver the grind.",
    "Focus the focus.",
    "Focus the momentum.",
    "Focus the progress.",
    "Focus the tasks.",
    "Focus the goals.",
    "Focus the effort.",
    "Focus the craft.",
    "Focus the hustle.",
    "Focus the discipline.",
    "Focus the curiosity.",
    "Focus the results.",
    "Focus the streak.",
    "Focus the energy.",
    "Focus the details.",
    "Focus the deadlines.",
    "Focus the growth.",
    "Focus the pride.",
    "Focus the pace.",
    "Focus the impact.",
    "Focus the grind.",
    "Grind the focus.",
    "Grind the momentum.",
    "Grind the progress.",
    "Grind the tasks.",
    "Grind the goals.",
    "Grind the effort.",
    "Grind the craft.",
    "Grind the hustle.",
    "Grind the discipline.",
    "Grind the curiosity.",
    "Grind the results.",
    "Grind the streak.",
    "Grind the energy.",
    "Grind the details.",
    "Grind the deadlines.",
    "Grind the growth.",
    "Grind the pride.",
    "Grind the pace.",
    "Grind the impact.",
    "Grind the grind.",
    "Rise the focus.",
    "Rise the momentum.",
    "Rise the progress.",
    "Rise the tasks.",
    "Rise the goals.",
    "Rise the effort.",
    "Rise the craft.",
    "Rise the hustle.",
    "Rise the discipline.",
    "Rise the curiosity.",
    "Rise the results.",
    "Rise the streak.",
    "Rise the energy.",
    "Rise the details.",
    "Rise the deadlines.",
    "Rise the growth.",
    "Rise the pride.",
    "Rise the pace.",
    "Rise the impact.",
    "Rise the grind.",
    "Tackle the focus.",
    "Tackle the momentum.",
    "Tackle the progress.",
    "Tackle the tasks.",
    "Tackle the goals.",
    "Tackle the effort.",
    "Tackle the craft.",
    "Tackle the hustle.",
    "Tackle the discipline.",
    "Tackle the curiosity.",
    "Tackle the results.",
    "Tackle the streak.",
    "Tackle the energy.",
    "Tackle the details.",
    "Tackle the deadlines.",
    "Tackle the growth.",
    "Tackle the pride.",
    "Tackle the pace.",
    "Tackle the impact.",
    "Tackle the grind.",
    "Nail the focus.",
    "Nail the momentum.",
    "Nail the progress.",
    "Nail the tasks.",
    "Nail the goals.",
    "Nail the effort.",
    "Nail the craft.",
    "Nail the hustle.",
    "Nail the discipline.",
    "Nail the curiosity.",
    "Nail the results.",
    "Nail the streak.",
    "Nail the energy.",
    "Nail the details.",
    "Nail the deadlines.",
    "Nail the growth.",
    "Nail the pride.",
    "Nail the pace.",
    "Nail the impact.",
    "Nail the grind.",
    "Spark the focus.",
    "Spark the momentum.",
    "Spark the progress.",
    "Spark the tasks.",
    "Spark the goals.",
    "Spark the effort.",
    "Spark the craft.",
    "Spark the hustle.",
    "Spark the discipline.",
    "Spark the curiosity.",
    "Spark the results.",
    "Spark the streak.",
    "Spark the energy.",
    "Spark the details.",
    "Spark the deadlines.",
    "Spark the growth.",
    "Spark the pride.",
    "Spark the pace.",
    "Spark the impact.",
    "Spark the grind.",
    "Move the focus.",
    "Move the momentum.",
    "Move the progress.",
    "Move the tasks.",
    "Move the goals.",
    "Move the effort.",
    "Move the craft.",
    "Move the hustle.",
    "Move the discipline.",
    "Move the curiosity.",
    "Move the results.",
    "Move the streak.",
    "Move the energy.",
    "Move the details.",
    "Move the deadlines.",
  ],
};

function dayOfYear(date) {
  const start = new Date(date.getFullYear(), 0, 0);
  return Math.floor((date - start) / 86_400_000);
}

function getTimeLabel(hour) {
  if (hour >= 5 && hour < 12) return "Good morning";
  if (hour >= 12 && hour < 17) return "Good afternoon";
  if (hour >= 17 && hour < 22) return "Good evening";
  return "Good night";
}

function roleKey(role) {
  if (role === "admin") return "ceo";
  if (role === "manager") return "manager";
  return "employee";
}

/** One unique quote per calendar day (1–365), per role. */
export function getHeaderGreeting(user) {
  const now = new Date();
  const key = roleKey(user?.role);
  const quotes = DAILY_QUOTES[key] || DAILY_QUOTES.employee;
  const idx = (dayOfYear(now) - 1) % quotes.length;
  const firstName = (user?.name || "there").split(/\s+/)[0];

  return {
    label: getTimeLabel(now.getHours()),
    quote: quotes[idx],
    firstName,
  };
}
